{% set name = "oxli" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oxli-{{ version }}.tar.gz
  sha256: 5d6903e92aadd3d2f9736b774d32ba71884a6115462fd8b1914a8dc3727ef3ad

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.1.0,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }} >=1.65.0
    - posix                               # [win]
    - make                                # [unix]
    - cargo-bundle-licenses
    - libclang                            # [unix]
    - clangdev                            # [unix]
    - xz
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python

test:
  imports:
    - oxli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dib-lab/oxli
  summary: k-mer tools
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ctb
